name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: meta
        run: echo "tag=sha-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build app image
        run: |
          docker build \
            --target runner \
            -t phuctranvn/equipment-maintenance:${{ steps.meta.outputs.tag }} \
            -t phuctranvn/equipment-maintenance:latest \
            .

      - name: Build migration image
        run: |
          docker build \
            --target migrator \
            -t phuctranvn/equipment-maintenance-migrator:${{ steps.meta.outputs.tag }} \
            .

      - name: Build seed image
        run: |
          docker build \
            --target seeder \
            -t phuctranvn/equipment-maintenance-seeder:${{ steps.meta.outputs.tag }} \
            .
      - name: Push seed image
        run: |
          docker push phuctranvn/equipment-maintenance-seeder:${{ steps.meta.outputs.tag }}

      - name: Push Docker images
        run: |
          docker push phuctranvn/equipment-maintenance:${{ steps.meta.outputs.tag }}
          docker push phuctranvn/equipment-maintenance:latest
          docker push phuctranvn/equipment-maintenance-migrator:${{ steps.meta.outputs.tag }}

      - name: Deploy to Azure VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: azureuser
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/equipment-maintenance

            export IMAGE_TAG=${{ steps.meta.outputs.tag }}

            docker compose pull app

            docker compose up -d

            docker image prune -f